# Generated by Django 3.2.5 on 2021-07-06 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resizer', '0002_alter_uploadedfiels_file_dir'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfiels',
            old_name='file_dir',
            new_name='file_uploaded',
        ),
        migrations.RemoveField(
            model_name='uploadedfiels',
            name='file_is_deleted',
        ),
        migrations.RemoveField(
            model_name='uploadedfiels',
            name='file_name',
        ),
    ]
