# Generated by Django 3.2.5 on 2021-07-06 15:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('resizer', '0006_rename_post_image_uploadedfiles_file_tn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ThumbnailSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptive_name', models.CharField(max_length=25)),
                ('thumbnail_width', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(28), django.core.validators.MaxValueValidator(2048)])),
                ('thumbnail_height', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(28), django.core.validators.MaxValueValidator(2048)])),
            ],
        ),
        migrations.RenameField(
            model_name='uploadedfiles',
            old_name='file_added',
            new_name='added',
        ),
        migrations.RenameField(
            model_name='uploadedfiles',
            old_name='file_user',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='uploadedfiles',
            name='file_tn',
        ),
        migrations.RemoveField(
            model_name='uploadedfiles',
            name='file_uploaded',
        ),
        migrations.AddField(
            model_name='uploadedfiles',
            name='name',
            field=models.CharField(default='aa', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedfiles',
            name='uploaded',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/%Y%m%d/'),
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='resizer.plan')),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='resizer.thumbnailsize'),
        ),
    ]
