# Generated by Django 3.2.5 on 2021-07-07 05:22

from django.db import migrations
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resizer', '0007_auto_20210706_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfiles',
            name='image_large',
            field=imagekit.models.fields.ProcessedImageField(default=django.utils.timezone.now, upload_to='images/%Y%m%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedfiles',
            name='image_small',
            field=imagekit.models.fields.ProcessedImageField(default=django.utils.timezone.now, upload_to='images/%Y%m%d/'),
            preserve_default=False,
        ),
    ]
