# Generated by Django 3.2.5 on 2021-07-07 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resizer', '0010_remove_uploadedfiles_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpireLink',
        ),
        migrations.RenameField(
            model_name='uploadedfiles',
            old_name='uploaded',
            new_name='file_uploaded',
        ),
    ]
