# Generated by Django 3.2.5 on 2021-07-07 06:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resizer', '0011_auto_20210707_0818'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpireLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated', models.DateTimeField(auto_now_add=True)),
                ('delay', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(3000)])),
            ],
        ),
    ]
