# Generated by Django 3.2.5 on 2021-07-07 07:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resizer', '0015_rename_delay_expirelink_delayed_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='expirelink',
            name='expire_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expirelink',
            name='generated',
            field=models.DateTimeField(),
        ),
    ]
