# Generated by Django 3.2.5 on 2021-07-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resizer', '0016_auto_20210707_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expirelink',
            name='expire_time',
            field=models.DateTimeField(null=True),
        ),
    ]
