# Generated by Django 3.2.5 on 2021-07-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resizer', '0017_alter_expirelink_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expirelink',
            name='generated',
            field=models.DateTimeField(null=True),
        ),
    ]
