# Generated by Django 3.2.5 on 2021-07-07 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resizer', '0019_uploadedfiles_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfiles',
            name='avatar',
        ),
    ]
