# Generated by Django 3.2.5 on 2021-07-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resizer', '0020_remove_uploadedfiles_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfiles',
            name='small_tnail',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/%Y%m%d/'),
        ),
    ]
