# Generated by Django 3.2.5 on 2021-07-07 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resizer', '0021_uploadedfiles_small_tnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfiles',
            name='small_tnail',
        ),
    ]
