# Generated by Django 3.2.5 on 2021-07-08 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resizer', '0022_remove_uploadedfiles_small_tnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='expirelink',
            name='files',
            field=models.ForeignKey(default=161, on_delete=django.db.models.deletion.DO_NOTHING, to='resizer.uploadedfiles'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedfiles',
            name='plan',
            field=models.ManyToManyField(to='resizer.Plan'),
        ),
    ]
