# Generated by Django 3.2.5 on 2021-07-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resizer', '0023_auto_20210708_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='size',
        ),
        migrations.AddField(
            model_name='plan',
            name='size',
            field=models.ManyToManyField(to='resizer.ThumbnailSize'),
        ),
    ]
