# Generated by Django 3.2.5 on 2021-07-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resizer', '0025_auto_20210708_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='get_expiring_link',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='get_orygiall',
            field=models.BooleanField(default=False),
        ),
    ]
